### ISSUE TITLE
US9: Indkomst rapport - Som kasserer vil jeg kunne genere en samlet oversigtsrapport over indkomst, så jeg kan planlægge foreningens økonomi

### ISSUE THREAD

**Issue by hajisan** [hajisan/repoDelfinen#36]
### TASKS

- [ ] 9.1 Opret Rapport-klassen og implementer en generer()-metode, der genererer en samlet rapport over de bedste svømmere i alle discipliner. 

**◔ESTIMERET TID: 3 TIMER**

- [ ] 9.2 Implementer ØkonomiRapport, der genererer rapporter over kontingentindkomst baseret på medlemsData. 

**◔ESTIMERET TID: 2 TIMER**

- [ ] 9.3 Implementer en rapportfunktion, der opdeler indkomst efter sæsoner (fx sommer og vinter). 

**◔ESTIMERET TID: 2 TIMER**
